language: node_js
node_js:
  - 12
before_install:
  - cd backend
  - npm update
  - python3 --version
  - pip --version
install:
  - npm install
notifications:
  email:
    on_success: change
    on_failure: change
